export const homeObjOne = {
    lightBg:false, 
    imgStart:'',
    lightTopLine:true,
    lightTextDesc:true,
    lightText:true,
    buttonLabel:'Get Started',
    topLine:'Marketing Agency',
    headline:'Lead Generation Specialist For Online Businessess',
    description:'We help business ownwers increase their revenue. Our team of unique specialists can help you achieve your business goals ',
    primary:true,
    img:(''),
    start:'',
    alt:'Image',
};

export const homeObjTwo = {
    lightBg:true, 
    imgStart:'start',
    lightTopLine:true,
    lightTextDesc:false,
    lightText:false,
    buttonLabel:'Get Started',
    topLine:'Marketing Agency',
    headline:'Lead Generation Specialist For Online Businessess',
    description:'We help business owners increase their revenue. Our team of unique specialists can help you achieve your business goals ',
    primary:false,
    img:require('../../images/undraw_work_in_progress_re_byic.svg').default,
    start:'true',
    alt:'Image',
};

export const homeObjThree = {
    lightBg:false, 
    imgStart:'',
    lightTopLine:true,
    lightTextDesc:true,
    lightText:true,
    buttonLabel:'Get Started',
    topLine:'Marketing Agency',
    headline:'Lead Generation Specialist For Online Businessess',
    description:'We help business owners increase their revenue. Our team of unique specialists can help you achieve your business goals ',
    primary:true,
    img:require('../../images/undraw_interior_design_re_7mvn.svg').default,
    start:'',
    alt:'Image',
};

export const homeObjFour = {
    lightBg:false, 
    imgStart:'start',
    lightTopLine:true,
    lightTextDesc:true,
    lightText:true,
    buttonLabel:'Get Started',
    topLine:'Marketing Agency',
    headline:'Lead Generation Specialist For Online Businessess',
    description:'We help business owners increase their revenue. Our team of unique specialists can help you achieve your business goals ',
    primary:true,
    img:require('../../images/undraw_engineering_team_a7n2.svg').default,
    start:'true ',
    alt:'Image',
};